// Copy the engine's figures into public/ before a build.
//
// They are not committed here. The originals live in packages/engine/docs/img
// and are generated by packages/engine/docs/make_figures.py, so regenerating
// them there updates both the engine README and this site. A second committed
// copy would drift the first time somebody regenerated one and not the other.
import { cp, mkdir, readdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const source = join(here, "..", "..", "engine", "docs", "img");
const target = join(here, "..", "public", "img");

await mkdir(target, { recursive: true });
const files = (await readdir(source)).filter((f) => f.endsWith(".png"));
if (files.length === 0) {
  console.error(`No figures found in ${source}.`);
  console.error("Run: python packages/engine/docs/make_figures.py");
  process.exit(1);
}
for (const file of files) {
  await cp(join(source, file), join(target, file));
}
console.log(`synced ${files.length} figures from packages/engine/docs/img`);
