"""Shared fixtures and geometry helpers for the test suite.

No test in this suite may touch the network or require an API key. Model and
VLM calls are mocked; every image is generated by ``tests/synth.py``.
"""

from __future__ import annotations

import sys
from pathlib import Path

import cv2
import numpy as np
import pytest

sys.path.insert(0, str(Path(__file__).parent))

import synth  # noqa: E402

pytest_plugins: list[str] = []


# --------------------------------------------------------------------------
# Geometry helpers
# --------------------------------------------------------------------------


def polygon_iou(a: np.ndarray, b: np.ndarray) -> float:
    """Intersection over union of two convex quadrilaterals."""
    a32 = np.asarray(a, dtype=np.float32)
    b32 = np.asarray(b, dtype=np.float32)
    inter_area, _ = cv2.intersectConvexConvex(a32, b32)
    if inter_area <= 0:
        return 0.0
    area_a = abs(cv2.contourArea(a32))
    area_b = abs(cv2.contourArea(b32))
    union = area_a + area_b - inter_area
    return float(inter_area / union) if union > 0 else 0.0


def angle_error(a: float, b: float) -> float:
    """Smallest angular difference in degrees, modulo the 90 degree symmetry.

    A rectangle detected as w x h at theta is the same rectangle as h x w at
    theta + 90, so the comparison has to fold into a 90 degree window.
    """
    d = abs(a - b) % 90.0
    return float(min(d, 90.0 - d))


def corners_angle(corners: np.ndarray) -> float:
    """Angle of the longer axis of a quadrilateral, in degrees."""
    pts = np.asarray(corners, dtype=np.float32)
    (_, _), (_, _), angle = cv2.minAreaRect(pts)
    return float(angle)


def best_match(target: np.ndarray, candidates: list[np.ndarray]) -> tuple[int, float]:
    """Index and IoU of the candidate quadrilateral closest to ``target``."""
    if not candidates:
        return -1, 0.0
    scores = [polygon_iou(target, c) for c in candidates]
    idx = int(np.argmax(scores))
    return idx, float(scores[idx])


# --------------------------------------------------------------------------
# Page fixtures
# --------------------------------------------------------------------------


# Pages are session scoped and never mutated. Building one is cheap, but
# splitting one is not, and the cache below is keyed on the image identity.


@pytest.fixture(scope="session")
def simple_page() -> synth.SyntheticPage:
    return synth.simple_page()


@pytest.fixture(scope="session")
def hard_page() -> synth.SyntheticPage:
    return synth.hard_page()


@pytest.fixture(scope="session")
def single_photo_page() -> synth.SyntheticPage:
    return synth.single_photo_page()


@pytest.fixture(scope="session")
def touching_pair_page() -> synth.SyntheticPage:
    return synth.touching_pair_page()


@pytest.fixture(scope="session")
def empty_page() -> synth.SyntheticPage:
    return synth.empty_page()


_SPLIT_CACHE: dict = {}


def split_cached(image, options):
    """``split_page`` memoised across the suite.

    Detection and refinement are deterministic, so running them twice on the
    same page with the same options can only produce the same answer. Several
    tests examine different aspects of the same result and the work is by far
    the most expensive thing the suite does.
    """
    from revelai.split import split_page

    key = (id(image), tuple(sorted(vars(options).items())))
    if key not in _SPLIT_CACHE:
        _SPLIT_CACHE[key] = split_page(image, options)
    return _SPLIT_CACHE[key]


@pytest.fixture
def pages_dir(tmp_path: Path) -> Path:
    """A folder of three synthetic pages, deliberately not in ASCII order.

    ``page_2`` before ``page_10`` is the point: ordering must be natural, so
    that a run over a folder of scans is reproducible and human sensible.
    """
    directory = tmp_path / "pages"
    synth.write_pages(
        directory,
        {
            "page_1.png": synth.simple_page(seed=10),
            "page_2.png": synth.touching_pair_page(seed=11),
            "page_10.png": synth.single_photo_page(seed=12),
        },
    )
    return directory


@pytest.fixture
def photos_dir(tmp_path: Path) -> Path:
    """A folder that looks like the output of ``split``: only photo_*.png."""
    from revelai.io import write_png
    from revelai.naming import photo_filename

    directory = tmp_path / "photos"
    directory.mkdir(parents=True, exist_ok=True)
    _, cast = synth.yellow_cast_image(size=(180, 140))
    for i in range(1, 4):
        write_png(directory / photo_filename(i), cast)
    return directory


def tree_digest(root: Path) -> dict[str, str]:
    """Map of relative path to SHA-256, used to prove a folder is untouched."""
    import hashlib

    out: dict[str, str] = {}
    for path in sorted(Path(root).rglob("*")):
        if path.is_file():
            out[str(path.relative_to(root))] = hashlib.sha256(path.read_bytes()).hexdigest()
    return out
