import Link from "next/link";
import { REPO } from "@/lib/content";

export function SiteFooter() {
  return (
    <footer className="border-t border-paper-200 bg-paper-100/60 dark:border-ink-800 dark:bg-ink-900/40">
      <div className="mx-auto max-w-6xl px-5 py-12">
        <div className="flex flex-col gap-6 sm:flex-row sm:items-start sm:justify-between">
          <div className="max-w-prose">
            <p className="font-semibold text-ink-900 dark:text-paper-100">
              Revel<span className="text-ember-700 dark:text-ember-400">AI</span>
            </p>
            <p className="mt-2 text-sm text-ink-700/80 dark:text-paper-300/80">
              Open source, MIT licensed. Every photograph on this site is
              synthetic — generated by the project&rsquo;s own test fixtures, not
              taken from anybody&rsquo;s album.
            </p>
          </div>
          <nav aria-label="Footer">
            <ul className="flex flex-wrap gap-x-6 gap-y-2 text-sm">
              <li>
                <a href={REPO} className="rounded underline underline-offset-4">
                  Repository
                </a>
              </li>
              <li>
                <Link
                  href="/honest-limitations/"
                  className="rounded underline underline-offset-4"
                >
                  Honest limitations
                </Link>
              </li>
              <li>
                <a
                  href={`${REPO}/blob/main/LICENSE`}
                  className="rounded underline underline-offset-4"
                >
                  MIT licence
                </a>
              </li>
            </ul>
          </nav>
        </div>
        <p className="mt-10 text-xs text-ink-700/80 dark:text-paper-300/70">
          Copyright &copy; 2026 Maiko Trindade.
        </p>
      </div>
    </footer>
  );
}
