"""Shared fixtures.

No test here touches the network or needs an API key. The engine is real - it is
fast enough and mocking it would test nothing - but every vision-language call
is a stand-in, and images are generated by the engine's own ``synth`` module
rather than committed.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

# The engine's fixture generator, so no image is ever committed to this package.
ENGINE_TESTS = Path(__file__).resolve().parents[2] / "engine" / "tests"
sys.path.insert(0, str(ENGINE_TESTS))

import synth  # noqa: E402

from revelai_mcp.config import ServerConfig  # noqa: E402


@pytest.fixture
def root(tmp_path: Path) -> Path:
    """A directory the server is allowed to touch."""
    directory = tmp_path / "album"
    directory.mkdir()
    return directory


@pytest.fixture
def config(root: Path) -> ServerConfig:
    return ServerConfig(roots=[root])


@pytest.fixture
def pages(root: Path) -> Path:
    """A folder holding two small album pages."""
    directory = root / "pages"
    synth.write_pages(
        directory,
        {
            "page_1.png": synth.tiny_page(seed=90, photos=2),
            "page_2.png": synth.tiny_page(seed=91, photos=1),
        },
    )
    return directory


@pytest.fixture
def photos(root: Path) -> Path:
    """A folder that looks like the output of split: only photo_*.png."""
    from revelai.io import write_png
    from revelai.naming import photo_filename

    directory = root / "photos"
    _, cast = synth.yellow_cast_image(size=(96, 72))
    for index in range(1, 3):
        write_png(
            directory / photo_filename(index),
            cast,
            text={"revelai:stage": "split", "revelai:source": "page_1.png"},
        )
    return directory


def tree_digest(path: Path) -> dict[str, str]:
    """Map of relative path to SHA-256, used to prove a folder is untouched."""
    import hashlib

    return {
        str(p.relative_to(path)): hashlib.sha256(p.read_bytes()).hexdigest()
        for p in sorted(path.rglob("*"))
        if p.is_file()
    }
